config/routes.rb
QualityTask::Application.routes.draw do

  resources :secret_codes, :only => [:index] do
    collection do
      post :create_n_secret_codes
    end
  end

  resources :users, :only => [:index]

  devise_for :users

  root :to => "homes#index"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  attr_accessible :name

  has_and_belongs_to_many :users
end

app/models/secret_code.rb
class SecretCode < ActiveRecord::Base
  attr_accessible :code, :user_id

  validates :code, :presence => true

  belongs_to :user

  SECRET_CODE_LENGTH = 16

  self.per_page = 10

  class << self
    def create_n_secret_codes(code_count = 10)
      self.connection.execute("insert into secret_codes (code, created_at, updated_at) values #{direct_insertion_values(code_count).join(",")}")
    end

    def direct_insertion_values(count)
      values = []
      count.to_i.times { values << "('#{SecureRandom.hex(SECRET_CODE_LENGTH)}', '#{Time.now}', '#{Time.now}')" }
      values
    end

    def unassigned_secret_codes
      @secret_codes ||= self.where(:user_id => nil )      
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :first_name, :last_name, 
                  :secret_code_attributes, :update_secret_code_relation

  attr_accessor :update_secret_code_relation

  validates :first_name, :presence => true
  validates :last_name, :presence => true
  validates :email, :presence => true,
            :uniqueness => true,
            :format => {:with => /^([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})$/i}
  validates :password, :presence => true

  has_one :secret_code
  has_and_belongs_to_many :roles

  accepts_nested_attributes_for :secret_code

  after_create :autosave_associated_records_for_secret_code
  after_create :create_user_role

  def admin?
    self.roles.collect{|role| role.name}.include?("admin")
  end

  def update_secret_code_relation=(secret_code_id)
    self.secret_code = SecretCode.find(secret_code_id)
  end

  def create_user_role
    self.role_ids = [2] # Normal User
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  #This is for new branch
  #This is for new branch
  protect_from_forgery

  before_filter :authenticate_user!, :redirect_www_to_normal

  def redirect_www_to_normal
    redirect_to request.url.gsub(/www./, "") unless request.url.scan(/\/\/www./).blank?
  end

  def render_404
    render :template => "errors/404", :format => [:html], :layout => "application"
  end

  def a
  end

  def b
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/secret_codes_controller.rb
class SecretCodesController < ApplicationController
  # GET /secret_codes
  # GET /secret_codes.json
  def index
    @secret_codes = SecretCode.paginate(:page => params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @secret_codes }
    end
  end

  # GET /secret_codes/1
  # GET /secret_codes/1.json
  def show
    @secret_code = SecretCode.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @secret_code }
    end
  end

  # GET /secret_codes/new
  # GET /secret_codes/new.json
  def new
    @secret_code = SecretCode.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @secret_code }
    end
  end

  # GET /secret_codes/1/edit
  def edit
    @secret_code = SecretCode.find(params[:id])
  end

  # POST /secret_codes
  # POST /secret_codes.json
  def create
    @secret_code = SecretCode.new(params[:secret_code])

    respond_to do |format|
      if @secret_code.save
        format.html { redirect_to @secret_code, notice: 'Secret code was successfully created.' }
        format.json { render json: @secret_code, status: :created, location: @secret_code }
      else
        format.html { render action: "new" }
        format.json { render json: @secret_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /secret_codes/1
  # PUT /secret_codes/1.json
  def update
    @secret_code = SecretCode.find(params[:id])

    respond_to do |format|
      if @secret_code.update_attributes(params[:secret_code])
        format.html { redirect_to @secret_code, notice: 'Secret code was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @secret_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /secret_codes/1
  # DELETE /secret_codes/1.json
  def destroy
    @secret_code = SecretCode.find(params[:id])
    @secret_code.destroy

    respond_to do |format|
      format.html { redirect_to secret_codes_url }
      format.json { head :no_content }
    end
  end

  def create_n_secret_codes
    SecretCode.create_n_secret_codes(params[:secret_code_count])

    respond_to do |format|
      format.html { redirect_to secret_codes_path, notice: "#{params[:secret_code_count]} Secret codes was created successfully" }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.paginate(:page => params[:pare])

    respond_to do |format|
      format.html
      format.json { render json: @users }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/secret_codes_helper.rb
module SecretCodesHelper

  def default_secret_code_count
    [[1, 1], [10, 10], [20, 20], [50, 50], [100, 100]]
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_flash_messages.html.erb
<% if notice.present? %>
  <div class="alert alert-success"><%= notice %><a class="close" data-dismiss="alert" href="#">×</a></div>
<% end %>
<% if alert.present? %>
  <div class="alert alert-error"><%= alert %><a class="close" data-dismiss="alert" href="#">×</a></div>
<% end %> 

app/views/application/_top_navigations.html.erb
<ul class="nav">
  <% if user_signed_in? %>
    <li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></li>
    <li><%= link_to "Edit Account", edit_user_registration_path %></li>
    <% if current_user.admin? %>
      <li><%= link_to "User Admin", users_path %></li>
      <li><%= link_to "Secret Admin", secret_codes_path %></li>
    <% end %>
  <% else %>  
    <li><%= link_to "Sign In", new_user_session_path %></li>
    <li><%= link_to "Sign Up", new_user_registration_path %></li>
  <% end %>
</ul>

app/views/homes/index.html.erb
<h1>Home</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Task</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
          <a class="brand" href="<%= root_path %>">Quality Task</a>
        <div class="nav-collapse">
          <%= render "top_navigations" %>
        </div>
      </div>
    </div>
  </div>

  <div class="container">
    <%= render "flash_messages" %>
    <div class="row">
      <div><%= yield %></div>
    </div>
  </div>

</body>
</html>

app/views/layouts/top_navigations.html.erb
<ul class="nav">
  <% if user_signed_in? %>
    <li><%= link_to "Browse Products", "" %></li>
    <li><%= link_to "Price List" %></li>
    <li><%= link_to "Contact Us" %></li>
    <li><%= link_to "Cart" %></li>
  <% else %>
    <li><%= link_to "Login", new_user_session_path %></li>
    <li><%= link_to "Sing Up", new_user_registration %></li>
  <% end %>
</ul>

app/views/secret_codes/_create_n_secret_codes.html.erb
<h1>Generate Secret codes</h1>
<%= form_tag(create_n_secret_codes_secret_codes_path) do %>
  <%= label_tag "How many codes do you want to generate" %>
  <%= select_tag :secret_code_count, options_for_select(default_secret_code_count, 10) %>
  <%= submit_tag "Generate" %>
<% end %>

app/views/secret_codes/_form.html.erb
<%= form_for @secret_code, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :code, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :code, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :user_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :user_id, :class => 'number_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                secret_codes_path, :class => 'btn' %>
  </div>
<% end %>

app/views/secret_codes/edit.html.erb
<%- model_class = @secret_code.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/secret_codes/index.html.erb
<%- model_class = SecretCode.new.class -%>
<div class="span9">
  <div class="page-header">
    <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
  </div>
  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= model_class.human_attribute_name(:id) %></th>
        <th><%= model_class.human_attribute_name(:code) %></th>
        <th><%= model_class.human_attribute_name(:user_id) %></th>
      </tr>
    </thead>
    <tbody>
      <% @secret_codes.each do |secret_code| %>
        <tr>
          <td><%= secret_code.id %></td>
          <td><%= secret_code.code %></td>
          <td><%= secret_code.user.try(:email) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= will_paginate(@secret_codes) unless @secret_codes.blank? %>
</div>
<div class="span3">
  <%= render "create_n_secret_codes" %>
</div>

app/views/secret_codes/new.html.erb
<%- model_class = @secret_code.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/secret_codes/show.html.erb
<%- model_class = @secret_code.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:code) %>:</strong></dt>
  <dd><%= @secret_code.code %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @secret_code.user_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              secret_codes_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_secret_code_path(@secret_code), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              secret_code_path(@secret_code),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>

app/views/users/_form.html.erb
<%= form_for @user, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :encrypted_password, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :encrypted_password, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :first_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :first_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :last_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :last_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :reset_password_token, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :reset_password_token, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :reset_password_sent_at, :class => 'control-label' %>
    <div class="controls">
      <%= f.datetime_select :reset_password_sent_at, :class => 'datetime_select' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :remember_created_at, :class => 'control-label' %>
    <div class="controls">
      <%= f.datetime_select :remember_created_at, :class => 'datetime_select' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :sign_in_count, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :sign_in_count, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :current_sign_in_at, :class => 'control-label' %>
    <div class="controls">
      <%= f.datetime_select :current_sign_in_at, :class => 'datetime_select' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :last_sign_in_at, :class => 'control-label' %>
    <div class="controls">
      <%= f.datetime_select :last_sign_in_at, :class => 'datetime_select' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :current_sign_in_ip, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :current_sign_in_ip, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :last_sign_in_ip, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :last_sign_in_ip, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                users_path, :class => 'btn' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<%- model_class = @user.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/index.html.erb
<%- model_class = User.new.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:first_name) %></th>
      <th><%= model_class.human_attribute_name(:last_name) %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate(@users) unless @users.blank? %>

app/views/users/new.html.erb
<%- model_class = @user.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<%- model_class = @user.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @user.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:encrypted_password) %>:</strong></dt>
  <dd><%= @user.encrypted_password %></dd>
  <dt><strong><%= model_class.human_attribute_name(:first_name) %>:</strong></dt>
  <dd><%= @user.first_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:last_name) %>:</strong></dt>
  <dd><%= @user.last_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:reset_password_token) %>:</strong></dt>
  <dd><%= @user.reset_password_token %></dd>
  <dt><strong><%= model_class.human_attribute_name(:reset_password_sent_at) %>:</strong></dt>
  <dd><%= @user.reset_password_sent_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:remember_created_at) %>:</strong></dt>
  <dd><%= @user.remember_created_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:sign_in_count) %>:</strong></dt>
  <dd><%= @user.sign_in_count %></dd>
  <dt><strong><%= model_class.human_attribute_name(:current_sign_in_at) %>:</strong></dt>
  <dd><%= @user.current_sign_in_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:last_sign_in_at) %>:</strong></dt>
  <dd><%= @user.last_sign_in_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:current_sign_in_ip) %>:</strong></dt>
  <dd><%= @user.current_sign_in_ip %></dd>
  <dt><strong><%= model_class.human_attribute_name(:last_sign_in_ip) %>:</strong></dt>
  <dd><%= @user.last_sign_in_ip %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              users_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_user_path(@user), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              user_path(@user),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>